variables:
  LOG_LEVEL: info
  NO_SCRIPTS: 'true'

  # Required to validate and test the gitlab modules
  GITLAB_TOKEN: $GITLAB_TERRATEST_TOKEN

stages:
  - analysis
  - test
  - release
  - notify

.base-rules:
  rules:
    ## Exclusive Rules
    # Current bug in gitlab rules will duplicate pipelines for open MRs
    - &not-mr-duplicate-pipeline
      if: $CI_MERGE_REQUEST_EVENT_TYPE == "detached"
      when: never
    - &not-mr-reminder
      if: $MERGE_REQUEST_REMINDER == "true"
      when: never
    - &not-on-schedules
      if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - &not-on-tags
      if: $CI_COMMIT_TAG
      when: never
    - &not-on-pipeline-trigger
      if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    ## Inclusive Rules
    - &on-tags
      if: $CI_COMMIT_TAG
      when: on_success
    - &on-azure-pipeline-trigger
      if: $CI_PIPELINE_SOURCE == "trigger" && $AZURE == "true"
      when: on_success
    - &on-gcp-pipeline-trigger
      if: $CI_PIPELINE_SOURCE == "trigger" && $GCP == "true"
      when: on_success
    - &run
      when: on_success

# Split test code to make file more readable
include:
  - '/_build/gitlab/terratest.yml'

.internal-runner:
  tags:
    - rocketmakers-internal-dind

.defaults:
  extends:
    - .internal-runner
  retry:
    max: 2
    when: runner_system_failure
  image: rocketmakers/ci-terraform-gcp:3.7.0
  before_script:
    - make install
  rules:
    - *not-mr-duplicate-pipeline
    - *not-mr-reminder
    - *not-on-pipeline-trigger
    - *not-on-schedules
    - *not-on-tags
    - *run

##############
## Validate ##
##############

validate:
  extends:
    - .defaults
  stage: analysis
  script:
    - make validate
    - make format-all
    - git diff HEAD --exit-code

##########
## Docs ##
##########

docs:
  extends:
    - .defaults
  stage: analysis
  script:
    - make generate-docs
    - git diff HEAD --exit-code

#############
## Release ##
#############

release:create-tag:
  extends:
    - .defaults
  stage: release
  script:
    - npx rocketmakers-tag --log=trace --pkgJsonPath=./package.json
  rules:
    - *not-mr-reminder
    - if: "$CI_COMMIT_BRANCH && $CI_COMMIT_TITLE =~ /Merge branch 'release\\/[0-9\\.a-zA-Z]+' into 'master'/"

notify:release:
  stage: notify
  image: rocketmakers/rm-slack:v0.1.3
  extends:
    - .internal-runner
  variables:
    ENV: production
    SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL_PLATFORM
  script:
    - 'cd /slack && npm run success -- -e=$ENV -v=$CI_COMMIT_TAG -m="A new version of rocketmakers terraform modules has been released. See the changelog for details: https://gitlab.com/rocketmakers/infrastructure/terraform-modules/-/blob/$CI_COMMIT_TAG/CHANGELOG.md"'
  rules:
    - *on-tags
    - *not-mr-reminder

############################
## Merge Request Reminder ##
############################

notify:merge-request-reminder:
  extends:
    - .defaults
  stage: notify
  image: bottlecapdave/gitlab-merge-request-reminder:1.3.0
  variables:
    SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL_PLATFORM
    GITLAB_PROJECT_IDS: $CI_PROJECT_ID
    INCLUDE_WIP: 'false'
    INCLUDE_DRAFT: 'false'
    SLACK_TARGET: ':eyes:'
  rules:
    - if: "$MERGE_REQUEST_REMINDER == 'true'"
    - *not-mr-duplicate-pipeline
  needs: []
  before_script: []
  script:
    - node /app/lib/index.js

.scalable-runner-test:
  image: rocketmakers/ci-deploy-k8s-az:3.8.0
  stage: analysis
  script:
    - sleep 10
    - echo "Hello world"

gcp-scalable-runner-test:
  extends: .scalable-runner-test
  rules:
    - *not-mr-duplicate-pipeline
    - *not-mr-reminder
    - *on-gcp-pipeline-trigger
    - *not-on-schedules
    - *not-on-tags
  tags:
    # Check the GITLAB Scalable Runner test
    - gcp-6faab9c3-9d73-4d51-ad84-d777b2d0cef0

azure-scalable-runner-test:
  extends: .scalable-runner-test
  rules:
    - *not-mr-duplicate-pipeline
    - *not-mr-reminder
    - *on-azure-pipeline-trigger
    - *not-on-schedules
    - *not-on-tags
  tags:
    # Check the GITLAB Scalable Runner test
    - azure-3308e4b9-3e83-470e-bb39-9cca0666b0fc
