variables:
  PROJECT_NAME: terraform-modules
  LOG_LEVEL: info

stages:
  - analysis
  - notify

.internal-runner:
  tags:
    - rocketmakers-internal-dind

.defaults:
  extends:
    - .internal-runner
  retry:
    max: 2
    when: runner_system_failure
  image: rocketmakers/ci-terraform-gcp:3.2.0
  before_script:
    - make install-node-modules

##############
## Validate ##
##############

validate:
  extends:
    - .defaults
  stage: analysis
  script:
    - make validate
    - make format-all
    - git diff HEAD --exit-code

##########
## Docs ##
##########

docs:
  extends:
    - .defaults
  stage: analysis
  script:
    - make generate-docs
    - git diff HEAD --exit-code

############################
## Merge Request Reminder ##
############################

notify:merge-requests:
  extends:
    - .internal-runner
  stage: notify
  image: bottlecapdave/gitlab-merge-request-reminder:v1.3.0
  only:
    variables:
      - $MERGE_REQUEST_REMINDER == "true"
  retry:
    max: 2
    when: runner_system_failure
  script:
    - node /app/lib/index.js
